name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (ou outra linguagem que esteja usando)
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # ou a versão que você estiver usando

    - name: Install dependencies
      run: npm install  # ou outro comando, conforme sua stack

    - name: Run tests
      run: npm test  # ou outro comando para executar os testes

    - name: Build project
      run: npm run build  # ou outro comando para build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        ssh user@server "cd C:\Users\nara.dutra.teixeira\Documents\treinamento && git pull origin main && npm install && npm run build"
